environments:
	dev:
		url: http://dev.example.com
		name: Developer Setup



    test:
        url: http://dev.example.com
        name: Developer Setup



    stage:
        url: http://dev.example.com
        name: Developer Setup



	prod:
		url: http://another.example.com
		name: My Cool App